services:
  qwen_api:
    build:
      context: .
      dockerfile: qwen_tts_api/Dockerfile
    container_name: qwen_api
    volumes:
     - .:/app
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
  db:
    image: mysql:latest
    container_name: DB
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./DataBase/data:/var/lib/mysql
      - ./DataBase/init.sql:/docker-entrypoint-initdb.d/init-db.sql