services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    ports:
      - "8000:8000"
    networks:
      - app-net

  tts:
    build:
      context: .
      dockerfile: Dockerfile.tts
    container_name: qwen-tts
    networks:
      - app-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /home/user/8TB/cap:/root/hdd

networks:
  app-net:
    driver: bridge