# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import server_communicate_pb2 as server__communicate__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in server_communicate_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpeechRelayStub(object):
    """Interface exported by the server.
    definition of service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Send = channel.unary_unary(
                '/SpeechRelay/Send',
                request_serializer=server__communicate__pb2.SpeechUploadRequest.SerializeToString,
                response_deserializer=server__communicate__pb2.UploadStatus.FromString,
                _registered_method=True)
        self.GetPendingMessages = channel.unary_stream(
                '/SpeechRelay/GetPendingMessages',
                request_serializer=server__communicate__pb2.UserIdentifier.SerializeToString,
                response_deserializer=server__communicate__pb2.MessageMetadata.FromString,
                _registered_method=True)
        self.GetVoice = channel.unary_stream(
                '/SpeechRelay/GetVoice',
                request_serializer=server__communicate__pb2.MessageIdentifier.SerializeToString,
                response_deserializer=server__communicate__pb2.AudioFrame.FromString,
                _registered_method=True)


class SpeechRelayServicer(object):
    """Interface exported by the server.
    definition of service
    """

    def Send(self, request, context):
        """Codelab Hint: Define RPC methods here

        송신측 -> 서버: 텍스트, 감정 데이터(전송 로직)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingMessages(self, request, context):
        """서버 -> 수신측: 메타데이터(접속 로직)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVoice(self, request, context):
        """서버 -> 수신측: 합성된 음성 데이터(재생 로직)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeechRelayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=server__communicate__pb2.SpeechUploadRequest.FromString,
                    response_serializer=server__communicate__pb2.UploadStatus.SerializeToString,
            ),
            'GetPendingMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPendingMessages,
                    request_deserializer=server__communicate__pb2.UserIdentifier.FromString,
                    response_serializer=server__communicate__pb2.MessageMetadata.SerializeToString,
            ),
            'GetVoice': grpc.unary_stream_rpc_method_handler(
                    servicer.GetVoice,
                    request_deserializer=server__communicate__pb2.MessageIdentifier.FromString,
                    response_serializer=server__communicate__pb2.AudioFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SpeechRelay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SpeechRelay', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpeechRelay(object):
    """Interface exported by the server.
    definition of service
    """

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SpeechRelay/Send',
            server__communicate__pb2.SpeechUploadRequest.SerializeToString,
            server__communicate__pb2.UploadStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/SpeechRelay/GetPendingMessages',
            server__communicate__pb2.UserIdentifier.SerializeToString,
            server__communicate__pb2.MessageMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/SpeechRelay/GetVoice',
            server__communicate__pb2.MessageIdentifier.SerializeToString,
            server__communicate__pb2.AudioFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
