# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server_communicate.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'server_communicate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18server_communicate.proto\"s\n\x13SpeechUploadRequest\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x13\n\x0breceiver_id\x18\x02 \x01(\t\x12\x0e\n\x06msg_id\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t\x12\x16\n\x0e\x65motion_vector\x18\x05 \x03(\x02\" \n\x0cUploadStatus\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\"!\n\x0eUserIdentifier\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"O\n\x11MessageIdentifier\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x11\n\tsender_id\x18\x02 \x01(\t\x12\x13\n\x0breceiver_id\x18\x03 \x01(\t\"F\n\x0fMessageMetadata\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x11\n\tsender_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"\\\n\nAudioFrame\x12\x15\n\raudio_content\x18\x01 \x01(\x0c\x12\x11\n\tsender_id\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\t\x12\x10\n\x08is_final\x18\x04 \x01(\x08\x32\xaa\x01\n\x0bSpeechRelay\x12-\n\x04Send\x12\x14.SpeechUploadRequest\x1a\r.UploadStatus\"\x00\x12;\n\x12GetPendingMessages\x12\x0f.UserIdentifier\x1a\x10.MessageMetadata\"\x00\x30\x01\x12/\n\x08GetVoice\x12\x12.MessageIdentifier\x1a\x0b.AudioFrame\"\x00\x30\x01\x42\x36\n\x1bio.grpc.examples.routeguideB\x0fRouteGuideProtoP\x01\xa2\x02\x03RTGb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_communicate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033io.grpc.examples.routeguideB\017RouteGuideProtoP\001\242\002\003RTG'
  _globals['_SPEECHUPLOADREQUEST']._serialized_start=28
  _globals['_SPEECHUPLOADREQUEST']._serialized_end=143
  _globals['_UPLOADSTATUS']._serialized_start=145
  _globals['_UPLOADSTATUS']._serialized_end=177
  _globals['_USERIDENTIFIER']._serialized_start=179
  _globals['_USERIDENTIFIER']._serialized_end=212
  _globals['_MESSAGEIDENTIFIER']._serialized_start=214
  _globals['_MESSAGEIDENTIFIER']._serialized_end=293
  _globals['_MESSAGEMETADATA']._serialized_start=295
  _globals['_MESSAGEMETADATA']._serialized_end=365
  _globals['_AUDIOFRAME']._serialized_start=367
  _globals['_AUDIOFRAME']._serialized_end=459
  _globals['_SPEECHRELAY']._serialized_start=462
  _globals['_SPEECHRELAY']._serialized_end=632
# @@protoc_insertion_point(module_scope)
